apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric8
  labels:
    volume_name: fabric8
  annotations:
    volume.beta.kubernetes.io/storage-class: standard
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  nfs:
    server: 10.130.24.100
    path: /shared
  persistentVolumeReclaimPolicy: Retain