apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric8
  namespace: fabric8
  labels:
    volume_name: fabric8
  annotations:
    volume.beta.kubernetes.io/storage-class: manual
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
  nfs:
    server: 10.130.24.100
    path: /shared
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    fabric8.io/target-platform: kubernetes
  creationTimestamp: null
  labels:
    group: io.fabric8.apps
    project: docker-registry
    provider: fabric8
    version: 1.0.1
  name: fabric8-docker-registry-storage
  namespace: fabric8
  selfLink: /api/v1/namespaces/fabric8/persistentvolumeclaims/fabric8-docker-registry-storage
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi